# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isadded',
            field=models.BooleanField(default=False),
        ),
    ]
